version: "3"

services:
  dataclay-backend:
    build: .
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_BACKEND_HOST=127.0.0.1
      - DATACLAY_BACKEND_ID=9662bd3e-0844-4688-bba5-29cac7d83531
    volumes:
      - ./model:/usr/src/model:ro
      - ./dataset:/usr/src/dataset:rw
    ports:
      - 6867:6867
    command: python -m dataclay.backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  dataclay-mds:
    build: .
    depends_on:
      - redis
    ports:
      - 16587:16587
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_PASSWORD=s3cret
      - DATACLAY_USERNAME=testuser
      - DATACLAY_DATASET=testdata
    command: python -m dataclay.metadata

